[general]
import = ["themes/rose-pine.toml"]

[env]
TERM = "xterm-256color"

[font.normal]
family = "monospace"
style = "Regular"

[font.italic]
family = "monospace"
style = "Italic"

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font]
size = 10.5
offset.x = 0
offset.y = 0

[window]
padding.x = 1
padding.y = 3
